[package]
name = "luau-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = { version = "^1.5.0", optional = true }
luau-lexer = { path = "../lexer" }
regex = { version = "1.11.1", optional = true }
serde = { version = "1.0.219", features = ["derive", "rc"], optional = true }
smol_str = { version = "0.3.2", features = ["serde"] }

[features]
default = ["cache"]
cache = []
lsp-ready = ["regex", "cache"]
raw-values = []
regex = ["dep:regex", "raw-values", "dep:lazy_static"]
serde = ["dep:serde"]

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
