[package]
name = "luau-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = { version = "1.4.0", optional = true }
regex = { version = "1.10.4", optional = true }
tree-sitter = "0.22.1"
tree-sitter-luau = { path = "../grammar" }

[features]
default = ["cache"]
cache = []
regex = ["dep:regex", "dep:lazy_static"]
