[package]
name = "luau-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter = "0.22.1"
tree-sitter-luau = { path = "../grammar" }
luau-parser-derive = { path = "../luau-parser-derive" }

[features]
default = ["cache"]
cache = []
