[package]
name = "luau-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
luau-lexer = { path = "../lexer" }
serde = { version = "1.0.219", features = ["derive", "rc"], optional = true }
smol_str = { version = "0.3.2" }

[features]
default = ["cache"]
cache = []
lsp-ready = ["cache", "raw-values"]
raw-values = []
serde = ["dep:serde", "smol_str/serde", "luau-lexer/serde"]

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
