[package]
name = "luau-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = { version = "1.4.0", optional = true }
lsp-types = { version = "0.95.1", optional = true }
regex = { version = "1.10.4", optional = true }
tree-sitter = "0.22.1"
tree-sitter-luau = { path = "../grammar" }

[features]
default = ["cache", "lsp-types"]
cache = []
lsp-types = ["dep:lsp-types"]
regex = ["dep:regex", "dep:lazy_static"]
