[package]
name = "luau-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = { version = "^1.5.0", optional = true }
regex = { version = "^1.10.6", optional = true }
serde = { version = "*", features = ["derive", "rc"], optional = true }
smol_str = { version = "0.2.2", features = ["serde"] }
tree-sitter = "^0.22.6"
tree-sitter-luau = { path = "../grammar" }

[features]
default = ["cache"]
cache = []
incremental-parsing = ["cache"]
lsp-ready = ["regex", "cache", "references"]
raw-values = []
references = ["dep:lazy_static"]
regex = ["dep:regex", "raw-values", "dep:lazy_static"]
serde = ["dep:serde"]

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "big_code"
harness = false
