[package]
name = "luau-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = { version = "^1.4.0", optional = true }
regex = { version = "^1.10.4", optional = true }
serde = { version = "*", features = ["derive", "rc"], optional = true }
smol_str = { version = "0.2.1", features = ["serde"] }
tree-sitter = "^0.22.1"
tree-sitter-luau = { path = "../grammar" }

[features]
default = ["cache"]
incremental-parsing = ["cache"]
cache = []
lsp-ready = ["regex", "cache"]
raw-values = []
regex = ["dep:regex", "raw-values", "dep:lazy_static"]
serde = ["dep:serde"]
